# Generated by Django 5.0.4 on 2024-04-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_comment_commenter_name_alter_comment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commenter_name',
        ),
    ]
