# Generated by Django 5.0.4 on 2024-04-23 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_like_unique_together_like_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='data',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
