# Generated by Django 5.0.4 on 2024-05-06 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0011_tag_photo_tags"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="like",
            unique_together={("user", "photo")},
        ),
        migrations.RemoveField(
            model_name="like",
            name="session_key",
        ),
    ]
